### ISSUE TITLE
Is the MobileNetv2 model is ready to download?

### ISSUE THREAD

**Issue by chowkamlee81** [chinakook/MobileNetV2.mxnet#1]
Is the MobileNetv2 model is ready to download?

**Comment by chinakook** [comment]
We get 65% accuracy only in the last traning, and we will release the model when we get 70%+

**Comment by daquexian** [comment]
@chinakook sorry to bother you, is your training finished now? I have tried different settings but the best accuracy is only ~70%

**Comment by chinakook** [comment]
@daquexian I updated symbol just now and a bug is fixed.

**Comment by chinakook** [comment]
@chowkamlee81 model is uploaded.

**Comment by daquexian** [comment]
Thanks for your effort!
