### ISSUE TITLE
Could you please share your training script?

### ISSUE THREAD

**Issue by daquexian** [chinakook/MobileNetV2.mxnet#2]
Thanks for your sharing your model. I trained mobilenetv2 using your latest symbol file by myself. But unfortunately I can only get 70.9% top-1 on imagenet 2012. I will be very appreciated if you could share your training script to help me check where I got wrong.

**Comment by chinakook** [comment]
70.9% is nice. Actually, I am busy with something else and this model is converted from other's implementation.

**Comment by daquexian** [comment]
Thanks!

**Comment by chinakook** [comment]
You can refer to the official Tensorflow implementation, it get 72.2% acc!!
https://github.com/tensorflow/models/blob/376dc8dd0999e6333514bcb8a6beef2b5b1bb8da/research/slim/nets/mobilenet/mobilenet_v2.py

**Comment by daquexian** [comment]
@chinakook Thanks for your information :)
